project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Website made by Edward F. Hillenaar with Quarto 2025"
  navbar:
    title: Edward F. Hillenaar
    right:
      - href: talks.qmd
        text: Talks
      - href: blog/index.qmd
        text: Blog
      - href: articles/index.qmd
        text: Article
      - href: contact.qmd
        text: Contact
    tools:
      - icon: github
        href: https://github.com/EdwardHill15
      
format:
  html:
    backgroundcolor: "#f2f8fb"
    #backgroundcolor: "#E8FAEA"
    fontcolor: "black"
    linkcolor: "black"
    mainfont: "sarif"
    fontsize: 20px
    theme: [cosmo, styles.scss]

